### ISSUE TITLE
UpDownCounter values are not properly reported as delta-gauges

### ISSUE THREAD

**Issue by jkwatson** [newrelic/opentelemetry-exporter-java#103] opened 2020-09-10 17:54 UTC
Currently, the UpDownCounters should be reported as gauges, where only the latest value is reported in an interval, but it doesn't appear this is working correctly. It appears they are being reported as gauges, but with the cumulative value, rather than the delta.

**Comment by jkwatson** [comment] 2020-09-10 17:56
Note: I suspect the problem might be here:  https://github.com/newrelic/opentelemetry-exporter-java/blob/ff4a4ae4dde2ace9f13ee209733b52995a719ed5/opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java#L57-L59

**Comment by breedx-nr** [comment] 2020-09-22 23:08
Looks like the name of the method doesn't match the implementation (it's backwards).  Doh.

We need to be careful that this doesn't break other things, and we should see what the Points look like for those UpDownCounters when they reach the adapter.  There's no trivial way to do that, so we should probably run a sample app to capture those and then reproduce.

**Comment by worekleszczy** [comment] 2021-02-23 00:24
Hi @jkwatson, I have an issue with pushing counters to NR and I guess it's might be related to this one.

Counter values are pushed to NR with cumulative values, making NRQL queries `SELECT sum(counter_name)` yield unexpected results.

According to [this](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/understand-data/metric-data-type) counter values should be reseted to 0 - I guess similar results would be achieved if deltas were used not only for gauges as it is right now but also for counters.

**Comment by jasonjkeller** [comment] 2021-04-28 20:49
Closing this issue as `wontfix` as this project has now been archived and will no longer be maintained. Please see the project [Archival Notice](https://github.com/newrelic/opentelemetry-exporter-java#archival-notice) for full details on the preferred options for sending OpenTelemetry data to the New Relic platform.

**Closed by jasonjkeller** 2021-04-28 20:49 UTC
Labels: bug, wontfix
